# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\"\x1b\n\x0b\x65\x63hoMessage\x12\x0c\n\x04text\x18\x01 \x01(\t23\n\x0b\x45\x63hoService\x12$\n\x04\x45\x63ho\x12\x0c.echoMessage\x1a\x0c.echoMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECHOMESSAGE._serialized_start=14
  _ECHOMESSAGE._serialized_end=41
  _ECHOSERVICE._serialized_start=43
  _ECHOSERVICE._serialized_end=94
# @@protoc_insertion_point(module_scope)
